"""NexaSphere AI Business Intelligence Assistant -- Streamlit prototype.

Every number on this page is produced by nexasphere.analytics /
nexasphere.insights (deterministic pandas computation). The optional local
LLM (Ollama) is only ever used to rephrase those numbers in plain English --
see nexasphere.nlg for the enforcement mechanism.
"""
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd
import plotly.express as px
import streamlit as st

sys.path.insert(0, str(Path(__file__).resolve().parent / "src"))

from nexasphere import analytics as an
from nexasphere import insights as ins
from nexasphere import nlg
from nexasphere import qa

st.set_page_config(page_title="NexaSphere AI Business Intelligence Assistant", page_icon="\U0001F4CA", layout="wide")

SEVERITY_COLOR = {"critical": "#d64545", "warning": "#e0a72e", "watch": "#3d7dd6", "info": "#3aa66b"}
SEVERITY_ICON = {"critical": "\U0001F534", "warning": "\U0001F7E0", "watch": "\U0001F535", "info": "\U0001F7E2"}


@st.cache_data(show_spinner=False)
def _cached_findings(window_days: int):
    findings = ins.generate_findings(window_days)
    return [f.as_dict() for f in findings]


@st.cache_data(show_spinner=False, ttl=60)
def _cached_narrate_finding(finding_dict: dict):
    """Wraps nlg.narrate_finding so every Streamlit rerun doesn't re-trigger
    an LLM call for all six findings. Without this, typing in the unrelated
    Ask tab, or expanding any panel, silently re-ran narration for every
    finding on every keystroke -- a real demo-responsiveness problem when
    Ollama is actually running (each call can take seconds).
    """
    finding = ins.Finding(**{k: finding_dict[k] for k in
                              ("id", "title", "category", "severity", "summary", "evidence", "recommendation")})
    result = nlg.narrate_finding(finding)
    return result.text, result.source, result.verified


def _llm_status_badge():
    available = nlg._ollama_available()
    if available:
        st.sidebar.success(f"Local LLM connected (Ollama · {nlg.OLLAMA_MODEL})")
    else:
        st.sidebar.info(
            "Local LLM not detected. Running on the deterministic template "
            "narrator -- every number below is still fully computed, just not "
            "rephrased by a model. Install Ollama and pull a model to enable "
            "richer narration (100% free)."
        )


def render_sidebar():
    st.sidebar.title("NexaSphere")
    st.sidebar.caption("AI Business Intelligence Assistant · BuildFest 2026")
    _llm_status_badge()
    st.sidebar.markdown("---")
    start, end = an.dataset_date_range()
    st.sidebar.markdown(f"**Dataset window**\n\n{start.date()} → {end.date()}")
    st.sidebar.markdown("---")
    st.sidebar.caption(
        "All KPIs are computed by a deterministic analytics engine. "
        "The AI layer only explains verified numbers -- it never invents them."
    )


def render_kpi_row():
    comp = an.revenue_profit_growth_gap(30)
    latest = comp["latest_period"]
    change = comp["change"]

    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Revenue (last 30d)", f"{latest['revenue']:,.0f}", f"{change['revenue_pct']:+.1f}%")
    c2.metric("Gross Profit (last 30d)", f"{latest['gross_profit']:,.0f}", f"{change['gross_profit_pct']:+.1f}%")
    c3.metric("Gross Margin", f"{latest['margin_pct']:.2f}%", f"{change['margin_pp']:+.2f} pp")
    c4.metric("Orders (last 30d)", f"{latest['orders']:,}", f"{change['orders_pct']:+.1f}%")

    if comp["margin_pressure"]:
        st.warning(
            f"⚠️ Revenue is growing ({change['revenue_pct']:+.1f}%) faster than gross profit "
            f"({change['gross_profit_pct']:+.1f}%) -- margin moved {change['margin_pp']:+.2f} pp. "
            "See the Findings tab for the evidence trail."
        )


def render_findings_tab():
    st.subheader("What needs management attention right now")
    st.caption(
        "Findings are generated by the insight engine from deterministic analytics "
        "output, ranked by severity. The narration is either produced by a local "
        "open-source LLM (if available) or a verified template -- both are "
        "grounded in the evidence shown below each card."
    )
    findings = _cached_findings(30)
    for f in findings:
        icon = SEVERITY_ICON.get(f["severity"], "⚪")
        confidence = f.get("confidence", "medium")
        with st.container(border=True):
            st.markdown(
                f"### {icon} {f['title']}  \n"
                f"`{f['severity'].upper()}` · {f['category']} · confidence: `{confidence.upper()}`"
            )
            text, source, _verified = _cached_narrate_finding(f)
            st.write(text)
            if source == "template":
                st.info("Verified analysis -- AI explanation unavailable or unverifiable right now; "
                        "the summary above is generated directly from the analytics engine, not a model.")
            else:
                st.caption(f"Narration source: AI (Ollama · {nlg.OLLAMA_MODEL}), numerically verified")
            if f.get("possible_drivers"):
                st.markdown("**Possible drivers (not confirmed -- worth investigating):**")
                for d in f["possible_drivers"]:
                    st.markdown(f"- {d}")
            st.markdown(f"**Recommended focus:** {f['recommendation']}")
            with st.expander("Evidence (raw computed values)"):
                st.json(f["evidence"])


def render_ask_tab():
    st.subheader("Ask a business question")
    st.caption("Answers are computed by the analytics engine, then phrased by the AI narration layer.")

    with st.expander("Try a suggested question"):
        for q in qa.SUGGESTED_QUESTIONS:
            if st.button(q, key=f"suggest_{q}"):
                st.session_state["question_input"] = q

    question = st.text_input("Your question", key="question_input", placeholder="e.g. Which marketing campaigns generate the best ROI?")
    if st.button("Ask", type="primary") and question.strip():
        with st.spinner("Computing verified answer..."):
            result = qa.answer_question(question)
        st.markdown(f"**Answer:** {result.narration.text}")
        if result.narration.source == "template":
            st.info("Verified analysis -- AI explanation unavailable or unverifiable right now; "
                    "the answer above is generated directly from the analytics engine, not a model.")
        else:
            st.caption(f"Narration source: AI (Ollama · {nlg.OLLAMA_MODEL}), numerically verified")
        st.caption(f"Matched intent: `{result.intent}`")
        with st.expander("Underlying computed result"):
            st.json(result.result)


def render_dashboard_tab():
    st.subheader("Business dashboards")

    trend = an.monthly_revenue_trend()
    fig = px.line(trend, x="month", y=["revenue", "gross_profit"], markers=True,
                   labels={"value": "Amount", "month": "Month", "variable": "Metric"},
                   title="Monthly Revenue vs. Gross Profit")
    st.plotly_chart(fig, use_container_width=True)

    col1, col2 = st.columns(2)
    with col1:
        cat = an.breakdown_by("category")
        fig2 = px.bar(cat, x="category", y="revenue", color="margin_pct",
                       title="Revenue & Margin by Category", color_continuous_scale="RdYlGn")
        st.plotly_chart(fig2, use_container_width=True)
    with col2:
        region = an.breakdown_by("region")
        fig3 = px.pie(region, names="region", values="revenue", title="Revenue Share by Region")
        st.plotly_chart(fig3, use_container_width=True)

    col3, col4 = st.columns(2)
    with col3:
        returns = an.return_analysis()
        fig4 = px.bar(returns, x="category", y="return_rate_pct", title="Return Rate % by Category")
        st.plotly_chart(fig4, use_container_width=True)
    with col4:
        delivery = an.delivery_partner_performance()
        fig5 = px.bar(delivery, x="partner_name", y="delayed_rate_pct", title="Delayed Delivery Rate % by Partner")
        st.plotly_chart(fig5, use_container_width=True)

    col5, col6 = st.columns(2)
    with col5:
        emp = an.employee_store_performance()
        fig6 = px.bar(emp, x="store_name", y="revenue_per_employee", color="margin_pct",
                       title="Revenue per Employee by Store", color_continuous_scale="RdYlGn")
        st.plotly_chart(fig6, use_container_width=True)
        st.caption("Sales are recorded per store, not per individual employee -- this reflects "
                   "store-level team performance, not individual attribution.")
    with col6:
        seg = an.customer_segment_value()
        fig7 = px.bar(seg, x="customer_segment", y="revenue_per_customer", color="margin_pct",
                       title="Revenue per Customer by Segment", color_continuous_scale="RdYlGn")
        st.plotly_chart(fig7, use_container_width=True)

    st.markdown("#### Marketing Campaign ROI")
    st.dataframe(an.campaign_roi()[["campaign_name", "channel", "spend", "attributed_revenue", "roi"]], use_container_width=True)

    st.markdown("#### Target vs. Actual (latest month)")
    tva = an.target_vs_actual()
    st.dataframe(
        tva[["store_name", "region", "revenue_target", "actual_revenue", "revenue_attainment_pct",
             "on_time_gap_pp", "return_rate_gap_pp"]],
        use_container_width=True,
    )


def main():
    render_sidebar()
    st.title("NexaSphere AI Business Intelligence Assistant")
    st.caption(
        "Turning disconnected retail data into prioritized management insights -- "
        "with every number traceable to a deterministic calculation."
    )
    render_kpi_row()
    tab1, tab2, tab3 = st.tabs(["🔎 Findings", "💬 Ask a Question", "📊 Dashboards"])
    with tab1:
        render_findings_tab()
    with tab2:
        render_ask_tab()
    with tab3:
        render_dashboard_tab()


if __name__ == "__main__":
    main()
